name: bioconvert

channels:
- bioconda
- conda-forge
- defaults
- r

dependencies:
- python=3.5.0
- colorlog
- biopython
- numpy
- matplotlib
- pandas
- scipy
- pysam
- pillow
- easydev>=0.9.34
- pip
- pyyaml
- pillow=4.0
- bedtools          # used in gallery and bam2bed
- singularity
- pigz
- dsrc
- sambamba
- bioawk
- seqtk
- graphviz=2.38   # provides dot for RTD
- icu=56

- pip:
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

